apiVersion: apps/v1
kind: Deployment
metadata:
  #  namespace: spring
  name: spring-kotlin-demo-deployment
  labels:
    app: spring-kotlin-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-kotlin-demo-deployment
  template:
    metadata:
      labels:
        app: spring-kotlin-demo-deployment
    spec:
      containers:
        - name: spring-kotlin-demo-deployment
          image: spring-kotlin-demo:0.1
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: spring-kotlin-demo-service
  labels:
    app: spring-kotlin-demo-service
    spring-boot: "true"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32081
  selector:
    app: spring-kotlin-demo-deployment
